version: '3.4'

services:
  dashboard:
    build: ./
    image: calendar-analyzer/dashboard
    env_file: ./.env
    environment:
      PORT: 8050
    ports:
      - "8050:8050"
    command: python app.py
